services:
  booking:
    build: .
    volumes:
      - .venv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    entrypoint:
      [
        "poetry",
        "run",
        "uvicorn",
        "api.main:app",
        "--host",
        "0.0.0.0",
        "--reload",
      ]
