services:
  booking:
    container_name: booking-web
    build: .
    volumes:
      - .venv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
  db:
    container_name: booking-db
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "booking"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data:
