services:
  db-test:
    container_name: booking-test-db
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "booking"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_test_data:/var/lib/mysql
    ports:
      - 33307:3306
volumes:
  mysql_data:
  mysql_test_data:
